Feature Engineering

Ziel: 

In diesem Notebook werden aus den historischen Premier-League-Daten aussagekräftige Merkmale (Features) erstellt.

Diese Merkmale dienen später als Eingabedaten für die Machine-Learning-Modelle (Logistische Regression und Neuronales Netz).

Feature	Beschreibung
HomeGoalsLast5:	Durchschnittliche Heimtore
AwayGoalsLast5:	Durchschnittliche Auswärtstore
HomeConcededLast5:	Durchschnittliche Heim-Gegentore
AwayConcededLast5:	Durchschnittliche Auswärts-Gegentore
HomeFormLast5:	Durchschnittliche Punkte aus den letzten 5 Heimspielen
AwayFormLast5:	Durchschnittliche Punkte aus den letzten 5 Auswärtsspielen

In [ ]:
import pandas as pd 
import os

# Tordurchschnitt der letzten 5 Spiele 

DATA_PATH = "../data/raw"

files = [f for f in os.listdir(DATA_PATH) if f.endswith(".csv")]

dfs = []

for file in files:
    df = pd.read_csv(os.path.join(DATA_PATH, file))
    df["Season"] = file.replace(",csv", "")
    dfs.append(df)

matches = pd.concat(dfs, ignore_index=True)

matches["Date"] = pd.to_datetime(matches["Date"], dayfirst=True)

matches = matches.sort_values("Date")

matches.reset_index(drop=True, inplace=True)

matches.head

C:\Users\HP\AppData\Local\Temp\ipykernel_7508\3383906470.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["Season"] = file.replace(",csv", "")

<bound method NDFrame.head of      Div       Date   Time        HomeTeam        AwayTeam  FTHG  FTAG FTR  \
0     E0 2021-08-13  20:00       Brentford         Arsenal     2     0   H
1     E0 2021-08-14  12:30      Man United           Leeds     5     1   H
2     E0 2021-08-14  15:00         Burnley        Brighton     1     2   A
3     E0 2021-08-14  15:00         Chelsea  Crystal Palace     3     0   H
4     E0 2021-08-14  15:00         Everton     Southampton     3     1   H
...   ..        ...    ...             ...             ...   ...   ...  ..
1895  E0 2026-05-24  16:00  Crystal Palace         Arsenal     1     2   A
1896  E0 2026-05-24  16:00         Burnley          Wolves     1     1   D
1897  E0 2026-05-24  16:00        Brighton      Man United     0     3   A
1898  E0 2026-05-24  16:00          Fulham       Newcastle     2     0   H
1899  E0 2026-05-24  16:00        West Ham           Leeds     3     0   H

      HTHG  HTAG  ... BMGMCA  BVCH  BVCD  BVCA  CLCH  CLCD  CLCA  LBCH  LBCD  \
0        1     0  ...    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1        1     0  ...    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2        1     0  ...    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
3        2     0  ...    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
4        0     1  ...    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
...    ...   ...  ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
1895     0     1  ...   1.82  4.00   3.8  1.85  3.90   3.6  1.91  3.90   3.6
1896     0     1  ...   2.75  2.38   3.6  2.80  2.40   3.4  2.80  2.40   3.4
1897     0     2  ...   3.35  1.85   4.1  3.70  1.91   4.0  3.60  1.85   4.0
1898     1     0  ...   2.43  2.55   3.6  2.55  2.50   3.6  2.60  2.50   3.6
1899     0     0  ...   4.35  1.70   4.1  4.50  1.73   4.2  4.33  1.70   4.0

      LBCA
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
...    ...
1895  1.91
1896  2.80
1897  3.50
1898  2.60
1899  4.20

[1900 rows x 163 columns]>

Feature 1: Heimtore im aktuellen Spiel

In [ ]:
matches[["HomeTeam", "FTHG"]].head()

     HomeTeam  FTHG
0   Brentford     2
1  Man United     5
2     Burnley     1
3     Chelsea     3
4     Everton     3

In [ ]:
# Durschnitttlih erzielte Tore der Heimmannschaft in den letzten 5 Spielen

matches["HomeGoalsLast5"] = (
    matches.groupby("HomeTeam")["FTHG"]
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

matches[["Date", "HomeTeam", "FTHG", "HomeGoalsLast5"]].head(15)

C:\Users\HP\AppData\Local\Temp\ipykernel_7508\998719365.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches["HomeGoalsLast5"] = (

         Date     HomeTeam  FTHG  HomeGoalsLast5
0  2021-08-13    Brentford     2             NaN
1  2021-08-14   Man United     5             NaN
2  2021-08-14      Burnley     1             NaN
3  2021-08-14      Chelsea     3             NaN
4  2021-08-14      Everton     3             NaN
5  2021-08-14    Leicester     1             NaN
6  2021-08-14      Watford     3             NaN
7  2021-08-14      Norwich     0             NaN
8  2021-08-15    Newcastle     2             NaN
9  2021-08-15    Tottenham     1             NaN
10 2021-08-21     Brighton     2             NaN
11 2021-08-21     Man City     5             NaN
12 2021-08-21        Leeds     2             NaN
13 2021-08-21  Aston Villa     2             NaN
14 2021-08-21    Liverpool     2             NaN

In [ ]:
# Durschnitttlih erzielte Tore der Auswärtsmannschaft in den letzten 5 Spielen

matches["AwayGoalsLast5"] = (
    matches.groupby("AwayTeam")["FTAG"]
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

matches[
    ["Date", "AwayTeam", "FTAG", "AwayGoalsLast5"]
].head(15)

C:\Users\HP\AppData\Local\Temp\ipykernel_7508\853304886.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches["AwayGoalsLast5"] = (

         Date        AwayTeam  FTAG  AwayGoalsLast5
0  2021-08-13         Arsenal     0             NaN
1  2021-08-14           Leeds     1             NaN
2  2021-08-14        Brighton     2             NaN
3  2021-08-14  Crystal Palace     0             NaN
4  2021-08-14     Southampton     1             NaN
5  2021-08-14          Wolves     0             NaN
6  2021-08-14     Aston Villa     2             NaN
7  2021-08-14       Liverpool     3             NaN
8  2021-08-15        West Ham     4             NaN
9  2021-08-15        Man City     0             NaN
10 2021-08-21         Watford     0             NaN
11 2021-08-21         Norwich     0             NaN
12 2021-08-21         Everton     2             NaN
13 2021-08-21       Newcastle     0             NaN
14 2021-08-21         Burnley     0             NaN

In [ ]:
# Wie viele Tore kassierte das Heimteam im Schnitt in seinen letzten 5 Heimspielen?

matches["HomeConcededLast5"] = (
    matches.groupby("HomeTeam")["FTAG"]
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

matches[
    ["Date", "HomeTeam", "FTAG", "HomeConcededLast5"]
].head(15)

C:\Users\HP\AppData\Local\Temp\ipykernel_7508\1333398541.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches["HomeConcededLast5"] = (

         Date     HomeTeam  FTAG  HomeConcededLast5
0  2021-08-13    Brentford     0                NaN
1  2021-08-14   Man United     1                NaN
2  2021-08-14      Burnley     2                NaN
3  2021-08-14      Chelsea     0                NaN
4  2021-08-14      Everton     1                NaN
5  2021-08-14    Leicester     0                NaN
6  2021-08-14      Watford     2                NaN
7  2021-08-14      Norwich     3                NaN
8  2021-08-15    Newcastle     4                NaN
9  2021-08-15    Tottenham     0                NaN
10 2021-08-21     Brighton     0                NaN
11 2021-08-21     Man City     0                NaN
12 2021-08-21        Leeds     2                NaN
13 2021-08-21  Aston Villa     0                NaN
14 2021-08-21    Liverpool     0                NaN

In [ ]:
# Wie viele Tore kassierte das Auswärtsteam im Schnitt in seinen letzten 5

matches["AwayConcededLast5"] = (
    matches.groupby("AwayTeam")["FTHG"]
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

matches[
    ["Date", "AwayTeam", "FTHG", "AwayConcededLast5"]
].head(15)

C:\Users\HP\AppData\Local\Temp\ipykernel_7508\4189519251.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches["AwayConcededLast5"] = (

         Date        AwayTeam  FTHG  AwayConcededLast5
0  2021-08-13         Arsenal     2                NaN
1  2021-08-14           Leeds     5                NaN
2  2021-08-14        Brighton     1                NaN
3  2021-08-14  Crystal Palace     3                NaN
4  2021-08-14     Southampton     3                NaN
5  2021-08-14          Wolves     1                NaN
6  2021-08-14     Aston Villa     3                NaN
7  2021-08-14       Liverpool     0                NaN
8  2021-08-15        West Ham     2                NaN
9  2021-08-15        Man City     1                NaN
10 2021-08-21         Watford     2                NaN
11 2021-08-21         Norwich     5                NaN
12 2021-08-21         Everton     2                NaN
13 2021-08-21       Newcastle     2                NaN
14 2021-08-21         Burnley     2                NaN

Form der Mannschaft

In [ ]:
# Punkte für das Heimteam 

matches["HomePoints"] = 0

matches.loc[matches["FTR"] == "H", "HomePoints"] = 3
matches.loc[matches["FTR"] == "D", "HomePoints"] = 1
matches.loc[matches["FTR"] == "A", "HomePoints"] = 0

matches[["HomeTeam", "FTR", "HomePoints"]].head(10)

C:\Users\HP\AppData\Local\Temp\ipykernel_7508\2438275223.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches["HomePoints"] = 0

     HomeTeam FTR  HomePoints
0   Brentford   H           3
1  Man United   H           3
2     Burnley   A           0
3     Chelsea   H           3
4     Everton   H           3
5   Leicester   H           3
6     Watford   H           3
7     Norwich   A           0
8   Newcastle   A           0
9   Tottenham   H           3

In [ ]:
# Punkte für das Auswärtsteam

matches["AwayPoints"] = 0

matches.loc[matches["FTR"] == "A", "AwayPoints"] = 3
matches.loc[matches["FTR"] == "D", "AwayPoints"] = 1
matches.loc[matches["FTR"] == "H", "AwayPoints"] = 0

matches[["AwayTeam", "FTR", "AwayPoints"]].head(10)

C:\Users\HP\AppData\Local\Temp\ipykernel_7508\2930803401.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches["AwayPoints"] = 0

         AwayTeam FTR  AwayPoints
0         Arsenal   H           0
1           Leeds   H           0
2        Brighton   A           3
3  Crystal Palace   H           0
4     Southampton   H           0
5          Wolves   H           0
6     Aston Villa   H           0
7       Liverpool   A           3
8        West Ham   A           3
9        Man City   H           0

In [ ]:
# Form der letzten 5 Heimspiele

matches["HomeFormLast5"] = (
    matches.groupby("HomeTeam")["HomePoints"]
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

matches[
    ["HomeTeam", "HomePoints", "HomeFormLast5"]
].head(15)

C:\Users\HP\AppData\Local\Temp\ipykernel_7508\2254829310.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches["HomeFormLast5"] = (

       HomeTeam  HomePoints  HomeFormLast5
0     Brentford           3            NaN
1    Man United           3            NaN
2       Burnley           0            NaN
3       Chelsea           3            NaN
4       Everton           3            NaN
5     Leicester           3            NaN
6       Watford           3            NaN
7       Norwich           0            NaN
8     Newcastle           0            NaN
9     Tottenham           3            NaN
10     Brighton           3            NaN
11     Man City           3            NaN
12        Leeds           1            NaN
13  Aston Villa           3            NaN
14    Liverpool           3            NaN

In [ ]:
# Form der letzten 5 Auswärtsspiele

matches["AwayFormLast5"] = (
    matches.groupby("AwayTeam")["AwayPoints"]
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

matches[
    ["AwayTeam", "AwayPoints", "AwayFormLast5"]
].head(15)

C:\Users\HP\AppData\Local\Temp\ipykernel_7508\2514745427.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches["AwayFormLast5"] = (

          AwayTeam  AwayPoints  AwayFormLast5
0          Arsenal           0            NaN
1            Leeds           0            NaN
2         Brighton           3            NaN
3   Crystal Palace           0            NaN
4      Southampton           0            NaN
5           Wolves           0            NaN
6      Aston Villa           0            NaN
7        Liverpool           3            NaN
8         West Ham           3            NaN
9         Man City           0            NaN
10         Watford           0            NaN
11         Norwich           0            NaN
12         Everton           1            NaN
13       Newcastle           0            NaN
14         Burnley           0            NaN

In [ ]:
# Splate BTTS fehlte, aus Notebook 01 nicht übernommen, jedes notebook sollte eigenständig sein.
matches["BTTS"] = (
    (matches["FTHG"] > 0) &
    (matches["FTAG"] > 0)
).astype(int)

matches["BTTS"].value_counts()

C:\Users\HP\AppData\Local\Temp\ipykernel_7508\1049021366.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches["BTTS"] = (

BTTS
1    1051
0     849
Name: count, dtype: int64

Features überprüfen

In [ ]:
feature_columns = [
    "HomeGoalsLast5",
    "AwayGoalsLast5",
    "HomeConcededLast5",
    "AwayConcededLast5",
    "HomeFormLast5",
    "AwayFormLast5",
    "BTTS"
]

matches[feature_columns].head(10)

,HomeGoalsLast5,AwayGoalsLast5,HomeConcededLast5,AwayConcededLast5,HomeFormLast5,AwayFormLast5,BTTS
0,NaN,NaN,NaN,NaN,NaN,NaN,0
1,NaN,NaN,NaN,NaN,NaN,NaN,1
2,NaN,NaN,NaN,NaN,NaN,NaN,1
3,NaN,NaN,NaN,NaN,NaN,NaN,0
4,NaN,NaN,NaN,NaN,NaN,NaN,1
5,NaN,NaN,NaN,NaN,NaN,NaN,0
6,NaN,NaN,NaN,NaN,NaN,NaN,1
7,NaN,NaN,NaN,NaN,NaN,NaN,0
8,NaN,NaN,NaN,NaN,NaN,NaN,1
9,NaN,NaN,NaN,NaN,NaN,NaN,0

Datensatz für das Machine Learning vorbereiten

In [ ]:
# Fehlende Werte prüfen

matches[feature_columns].isnull().sum()

HomeGoalsLast5       27
AwayGoalsLast5       27
HomeConcededLast5    27
AwayConcededLast5    27
HomeFormLast5        27
AwayFormLast5        27
BTTS                  0
dtype: int64

In [ ]:
# NaN-Zeilen entfernen

matches = matches.dropna(subset=[
    "HomeGoalsLast5",
    "AwayGoalsLast5",
    "HomeConcededLast5",
    "AwayConcededLast5",
    "HomeFormLast5",
    "AwayFormLast5"
])

matches.reset_index(drop=True, inplace=True)

print(matches.shape)

(1866, 172)

In [ ]:
import os

os.makedirs("../data/processed", exist_ok=True)

matches.to_csv("../data/Processed/btts_features.csv", index=False)

print ("✅ Datensatz gespeichert")

✅ Datensatz gespeichert